import { createSlice } from "@reduxjs/toolkit";

const products = [
  {
    id: "001",
    image: "images/1.jpg",
    company: "Carlton London",
    item_name: "Rhodium-Plated CZ Floral Studs",
    original_price: 1045,
    current_price: 606,
    discount_percentage: 42,
    return_period: 14,
    delivery_date: "10 Oct 2023",
    rating: { stars: 4.5, count: 1400 },
  },
  {
    id: "002",
    image: "images/2.jpg",
    company: "CUKOO",
    item_name: "Women Padded Halter Neck Swimming Dress",
    original_price: 2599,
    current_price: 1507,
    discount_percentage: 42,
    return_period: 14,
    delivery_date: "10 Oct 2023",
    rating: { stars: 4.3, count: 24 },
  },
  {
    id: "003",
    image: "images/3.jpg",
    company: "NUEVOSDAMAS",
    item_name: "Women Red & White Printed A-Line Knee-Length Skirts",
    original_price: 1599,
    current_price: 495,
    discount_percentage: 69,
    return_period: 14,
    delivery_date: "10 Oct 2023",
    rating: { stars: 4.1, count: 249 },
  },
  {
    id: "004",
    image: "images/4.jpg",
    company: "ADIDAS",
    item_name: "Indian Cricket ODI Jersey",
    original_price: 999,
    current_price: 999,
    discount_percentage: 0,
    return_period: 14,
    delivery_date: "10 Oct 2023",
    rating: { stars: 5, count: 10 },
  },
  {
    id: "005",
    image: "images/5.jpg",
    company: "Roadster",
    item_name: "Pure Cotton T-shirt",
    original_price: 1399,
    current_price: 489,
    discount_percentage: 65,
    return_period: 14,
    delivery_date: "10 Oct 2023",
    rating: { stars: 4.2, count: 3500 },
  },
  {
    id: "006",
    image: "images/6.jpg",
    company: "Nike",
    item_name: "Men ReactX Running Shoes",
    original_price: 14995,
    current_price: 14995,
    discount_percentage: 0,
    return_period: 14,
    delivery_date: "10 Oct 2023",
    rating: { stars: 0, count: 0 },
  },
  {
    id: "007",
    image: "images/7.jpg",
    company: "The Indian Garage Co",
    item_name: "Men Slim Fit Regular Shorts",
    original_price: 1599,
    current_price: 639,
    discount_percentage: 60,
    rating: { stars: 4.2, count: 388 },
  },
  {
    id: "008",
    image: "images/8.jpg",
    company: "Nivea",
    item_name: "Men Fresh Deodrant 150ml",
    original_price: 285,
    current_price: 142,
    discount_percentage: 50,
    return_period: 14,
    delivery_date: "10 Oct 2023",
    rating: { stars: 4.2, count: 5200 },
  },
  {
    id: "009",
    image: "https://m.media-amazon.com/images/I/61XtYoH-kGL._AC_UY327_FMwebp_QL65_.jpg",
    company: "ZEBRONICS",
    item_name: "ZEBRONICS ZEB-JAGUAR Wireless Mouse",
    original_price: 1190,
    current_price: 279,
    discount_percentage: 77,
    return_period: 14,
    delivery_date: "05 Nov 2024",
    rating: { stars: 4.2, count: 7800 },
  },
  {
    id: "010",
    image: "https://m.media-amazon.com/images/I/61kvIiso70L._AC_UL480_FMwebp_QL65_.jpg",
    company: "ZEBRONICS",
    item_name: "ZEBRONICS Marine Wireless Mouse",
    original_price: 1699,
    current_price: 699,
    discount_percentage: 59,
    return_period: 14,
    delivery_date: "05 Nov 2024",
    rating: { stars: 4.2, count: 4200 },
  },
  {
    id: "011",
    image: "https://m.media-amazon.com/images/I/71ItMeqpN3L._SL1500_.jpg",
    company: "Apple",
    item_name: "Apple 2024 MacBook Air 13",
    original_price: 134900,
    current_price: 122990,
    discount_percentage: 9,
    return_period: 14,
    delivery_date: "05 Nov 2024",
    rating: { stars: 4.2, count: 14200 },
  },
  {
    id: "012",
    image: "https://m.media-amazon.com/images/I/714gtA8+m3L._SL1500_.jpg",
    company: "LG",
    item_name: "LG Automatic Washing Machine ",
    original_price: 53990,
    current_price: 39990,
    discount_percentage: 26,
    return_period: 14,
    delivery_date: "05 Nov 2024",
    rating: { stars: 4.2, count: 3215 },
  },
  {
    id: "013",
    image: "https://m.media-amazon.com/images/I/6175SlKKECL._SL1500_.jpg",
    company: "OnePlus",
    item_name: "OnePlus Nord CE 3 5G ",
    original_price: 26999,
    current_price: 16999,
    discount_percentage: 37,
    return_period: 14,
    delivery_date: "25 Nov 2024",
    rating: { stars: 4.4, count: 1200 },
  },
  {
    id: "014",
    image: "https://m.media-amazon.com/images/I/61YNB13-F9L._SL1500_.jpg",
    company: "Philips",
    item_name: "Philips Skin Friendly Trimmer",
    original_price: 1599,
    current_price: 999,
    discount_percentage: 38,
    return_period: 14,
    delivery_date: "05 Nov 2024",
    rating: { stars: 4.2, count: 67872 },
  },
  {
    id: "015",
    image: "https://images-eu.ssl-images-amazon.com/images/I/61erXkfqw7L._AC_UL165_SR165,165_.jpg",
    company: "ZEBRONICS",
    item_name: "ZEBRONICS 2.4GHz Wireless Keyboard & Mouse Combo",
    original_price: 1899,
    current_price: 899,
    discount_percentage: 53,
    return_period: 14,
    delivery_date: "05 Nov 2024",
    rating: { stars: 4.2, count: 53 },
  },
];

const itemSlice = createSlice({
  name: "item",
  initialState: products,
  reducers: {
    addProductsData: (state, action) => {
      return action.payload.fetchingData;
    },
  },
});

export const ItemAction = itemSlice.actions;
export default itemSlice;
