import { createSlice } from "@reduxjs/toolkit";

export const products = [
  {
    id: "001",
    image: "https://m.media-amazon.com/images/I/81Zee0f1HNL._SL1500_.jpg",
    company: "Carlton London",
    item_name:
      "Roseate Mosaic Super Soft Bath Mat Super Absorbent Anti-Skid Door Mats for Home/Bathroom Mat/Bedroom/Kitchen/Floor Mat",
    original_price: 1045,
    current_price: 606,
    discount_percentage: 42,
    return_period: 14,
    delivery_date: "10 Oct 2023",
    rating: { stars: 4.5, count: 1400 },
  },
  {
    id: "002",
    image:
      "https://m.media-amazon.com/images/I/81lUuQcAcML._AC_UL480_FMwebp_QL65_.jpg",
    company: "Amazon",
    item_name: "Solimo Polyester Spandex Dining Chair Slipcover ",
    original_price: 2599,
    current_price: 1507,
    discount_percentage: 42,
    return_period: 14,
    delivery_date: "10 Oct 2023",
    rating: { stars: 4.3, count: 24 },
  },
  {
    id: "003",
    image: "https://m.media-amazon.com/images/I/71ddRfhOCIL._SL1500_.jpg",
    company: "Crompton",
    item_name:
      "Crompton Ozone Desert Air Cooler- 75L; with Everlast Pump, Auto Fill, 4-Way Air Deflection and High Density Honeycomb Pads; White & Teal",
    original_price: 1599,
    current_price: 495,
    discount_percentage: 69,
    return_period: 14,
    delivery_date: "10 Oct 2023",
    rating: { stars: 4.1, count: 249 },
  },
  {
    id: "004",
    image: "https://m.media-amazon.com/images/I/71QfUcEOg8L._SL1500_.jpg",
    company: "Amazon Basics",
    item_name:
      "amazon basics High Speed 55 Watt Oscillating Pedestal Fan, 400Mm Sweep Length, White (without Remote)",
    original_price: 999,
    current_price: 999,
    discount_percentage: 0,
    return_period: 14,
    delivery_date: "10 Oct 2023",
    rating: { stars: 5, count: 10 },
  },
  {
    id: "005",
    image: "https://m.media-amazon.com/images/I/71vJLCZBeoL._SL1500_.jpg",
    company: "AGARO",
    item_name:
      "AGARO Marvel 9L Oven Toaster Griller, Cake Baking, Grilling, Toasting, OTG, 800 Watts, (Black)",
    original_price: 1399,
    current_price: 489,
    discount_percentage: 65,
    return_period: 14,
    delivery_date: "10 Oct 2023",
    rating: { stars: 4.2, count: 3500 },
  },
  {
    id: "006",
    image: "https://m.media-amazon.com/images/I/51-pLhPHoBL._SY741_.jpg",
    company: "CB-COLEBROOK",
    item_name:
      "CB-COLEBROOK Men's Casual Button Down Shirts Long Sleeve Linen Shirt Fashion Textured Beach Summer Shirt",
    original_price: 14995,
    current_price: 14995,
    discount_percentage: 0,
    return_period: 14,
    delivery_date: "10 Oct 2023",
    rating: { stars: 0, count: 0 },
  },
  {
    id: "007",
    image: "https://m.media-amazon.com/images/I/61ybeKQto8L._SY879_.jpg",
    company: "Casio",
    item_name:
      "Casio Vintage A158WA-1DF Black Digital Dial Silver Stainless Steel Band D011",
    original_price: 1599,
    current_price: 639,
    discount_percentage: 60,
    rating: { stars: 4.2, count: 388 },
  },
  {
    id: "008",
    image: "https://m.media-amazon.com/images/I/71mX4WATh-L._SX679_.jpg",
    company: "GoSriKi",
    item_name:
      "GoSriKi Women's Rayon Blend Anarkali Printed Kurta with Palazzo & Dupatta",
    original_price: 285,
    current_price: 142,
    discount_percentage: 50,
    return_period: 14,
    delivery_date: "10 Oct 2023",
    rating: { stars: 4.2, count: 5200 },
  },
  {
    id: "009",
    image:
      "https://m.media-amazon.com/images/I/61XtYoH-kGL._AC_UY327_FMwebp_QL65_.jpg",
    company: "ZEBRONICS",
    item_name: "ZEBRONICS ZEB-JAGUAR Wireless Mouse",
    original_price: 1190,
    current_price: 279,
    discount_percentage: 77,
    return_period: 14,
    delivery_date: "05 Nov 2024",
    rating: { stars: 4.2, count: 7800 },
  },
  {
    id: "010",
    image:
      "https://m.media-amazon.com/images/I/61kvIiso70L._AC_UL480_FMwebp_QL65_.jpg",
    company: "ZEBRONICS",
    item_name: "ZEBRONICS Marine Wireless Mouse",
    original_price: 1699,
    current_price: 699,
    discount_percentage: 59,
    return_period: 14,
    delivery_date: "05 Nov 2024",
    rating: { stars: 4.2, count: 4200 },
  },
  {
    id: "011",
    image: "https://m.media-amazon.com/images/I/71ItMeqpN3L._SL1500_.jpg",
    company: "Apple",
    item_name: "Apple 2024 MacBook Air 13",
    original_price: 134900,
    current_price: 122990,
    discount_percentage: 9,
    return_period: 14,
    delivery_date: "05 Nov 2024",
    rating: { stars: 4.2, count: 14200 },
  },
  {
    id: "012",
    image: "https://m.media-amazon.com/images/I/714gtA8+m3L._SL1500_.jpg",
    company: "LG",
    item_name: "LG Automatic Washing Machine ",
    original_price: 53990,
    current_price: 39990,
    discount_percentage: 26,
    return_period: 14,
    delivery_date: "05 Nov 2024",
    rating: { stars: 4.2, count: 3215 },
  },
  {
    id: "013",
    image: "https://m.media-amazon.com/images/I/6175SlKKECL._SL1500_.jpg",
    company: "OnePlus",
    item_name: "OnePlus Nord CE 3 5G ",
    original_price: 26999,
    current_price: 16999,
    discount_percentage: 37,
    return_period: 14,
    delivery_date: "25 Nov 2024",
    rating: { stars: 4.4, count: 1200 },
  },
  {
    id: "014",
    image: "https://m.media-amazon.com/images/I/61YNB13-F9L._SL1500_.jpg",
    company: "Philips",
    item_name: "Philips Skin Friendly Trimmer",
    original_price: 1599,
    current_price: 999,
    discount_percentage: 38,
    return_period: 14,
    delivery_date: "05 Nov 2024",
    rating: { stars: 4.2, count: 67872 },
  },
  {
    id: "015",
    image:
      "https://images-eu.ssl-images-amazon.com/images/I/61erXkfqw7L._AC_UL165_SR165,165_.jpg",
    company: "ZEBRONICS",
    item_name: "ZEBRONICS 2.4GHz Wireless Keyboard & Mouse Combo",
    original_price: 1899,
    current_price: 899,
    discount_percentage: 53,
    return_period: 14,
    delivery_date: "05 Nov 2024",
    rating: { stars: 4.2, count: 53 },
  },
];

const itemSlice = createSlice({
  name: "item",
  initialState: products,
  reducers: {
    addProductsData: (state, action) => {
      return action.payload.fetchingData;
    },
  },
});

export const ItemAction = itemSlice.actions;
export default itemSlice;
